/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface DataFlowChildren {
        "indx": number;
        "info": any;
        "isActive": boolean;
    }
    interface DataFlowParent {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDataFlowChildrenElement extends Components.DataFlowChildren, HTMLStencilElement {
    }
    var HTMLDataFlowChildrenElement: {
        prototype: HTMLDataFlowChildrenElement;
        new (): HTMLDataFlowChildrenElement;
    };
    interface HTMLDataFlowParentElement extends Components.DataFlowParent, HTMLStencilElement {
    }
    var HTMLDataFlowParentElement: {
        prototype: HTMLDataFlowParentElement;
        new (): HTMLDataFlowParentElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "data-flow-children": HTMLDataFlowChildrenElement;
        "data-flow-parent": HTMLDataFlowParentElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface DataFlowChildren {
        "indx"?: number;
        "info"?: any;
        "isActive"?: boolean;
        "onUserSelect"?: (event: CustomEvent<any>) => void;
    }
    interface DataFlowParent {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "data-flow-children": DataFlowChildren;
        "data-flow-parent": DataFlowParent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "data-flow-children": LocalJSX.DataFlowChildren & JSXBase.HTMLAttributes<HTMLDataFlowChildrenElement>;
            "data-flow-parent": LocalJSX.DataFlowParent & JSXBase.HTMLAttributes<HTMLDataFlowParentElement>;
        }
    }
}
